### ISSUE TITLE
Error: The network connection encountered a problem

### ISSUE THREAD

**Issue by zvictor** [fauna/fauna-js#225]
## Description

I am facing errors that at first seem very generic (i.e. network connection) and not Fauna related. However, by [Googleing the error](https://letmegooglethat.com/?q=%22The+network+connection+encountered+a+problem%22) we only find a single result and it's also thrown by Fauna:

https://github.com/oven-sh/bun/issues/6204 - Network connection issue using FaunaDB JS SDK 

## Error

```haskell
[Unhandled Rejection] NetworkError: Unexpected message handler failure: The network connection encountered a problem.
    at _NodeHTTP2Client.request (/node_modules/.pnpm/fauna@1.3.1/node_modules/fauna/src/http-client/node-http2-client.ts:94:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _Client.query_fn (/node_modules/.pnpm/fauna@1.3.1/node_modules/fauna/src/client.ts:451:24)
    at async updateUser (file:///services/whatsapp-listener/store.ts:46:18)
    at async file:///services/whatsapp-listener/bot/index.ts:140:9
    at async Consumer.handleMessage (file:///packages/events/index.ts:37:19)
    at async Consumer.executeHandler (/node_modules/.pnpm/sqs-consumer@7.0.3/node_modules/sqs-consumer/dist/consumer.js:310:26)
    at async Consumer.processMessage (/node_modules/.pnpm/sqs-consumer@7.0.3/node_modules/sqs-consumer/dist/consumer.js:193:34)
    at async Promise.all (index 0)
    at async Consumer.handleSqsResponse (/node_modules/.pnpm/sqs-consumer@7.0.3/node_modules/sqs-consumer/dist/consumer.js:173:17) {
  [cause]: Error [ERR_HTTP2_ERROR]: Protocol error
      at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
      at new NghttpError (node:internal/http2/util:556:5)
      at Http2Session.onSessionInternalError (node:internal/http2/core:792:26) {
    code: 'ERR_HTTP2_ERROR',
    errno: -505
  }
}
```

## Code

```ts
  import { Client, fql } from 'fauna'
  const client = new Client()

  const exp = fql`
    let doc = UserProfile.firstWhere(
      .identifier == "${id}"
    )
    
    if (doc == null) {
      UserProfile.create({
        identifier: "${id}",
        name: "${name}"
      })
    } else {
      doc!.update({
        name: "${name}"
      })
    }
    `

  const result = await client.query<UserProfile>(exp)
  ```

**Comment by zvictor** [comment]
Okay, the problem was on my configuration.
I am migrating from brainyduck to fql v10 and both of them make use of `FAUNA_ENDPOINT` with different values.

Thus, the error above shows because `FAUNA_ENDPOINT` was set as `https://graphql.us.fauna.com/graphql` instead of `https://db.fauna.com/`.

---

Feel free to close this issue. I am not closing yet as this issue might raise the question if there is any improvement that can be made to the error message.
